project:
  type: website

website:
  title: "Comp. Soc. Sci. for Sustainability (EBS 181/281)"
  favicon: Logo.png
  navbar:
    background: "#8C1515"
    foreground: "#FFFFFF"
    right:
      - href: index.qmd
        text: Course information and syllabus

      - href: book/index.qmd
        text: Book

      - href: lectures/index.qmd
        text: Lectures

      - href: labs/index.qmd
        text: "Lab exercises"

      - href: https://mt.digital
        text: "MA Turner, Ph.D."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: /users/mt/workspace/Writing/library.bib
